Repository AY2223S2-CS2103T-T11-2/tp, pull requests merged in 2023-03, with the labels that each got.

#54 Add Edit command
  docs/team/jeremykhoo-nus.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditMeetingsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMeetingParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: type.Story, type.Task

#66 Fix AddMeetingCommand
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: type.Bug

#67 Implement shortcut to traverse commands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/command/CommandHistory.java
  src/main/java/seedu/address/model/command/exceptions/OutOfBoundsCommandHistoryException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/command/CommandHistoryTest.java
Labels: type.Enhancement

#69 editm can now edit person
  src/main/java/seedu/address/logic/commands/EditMeetingsCommand.java
  src/main/java/seedu/address/logic/parser/EditMeetingParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#70 Varying input formats for `DateTime`
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/exceptions/InvalidDateTimeFormatException.java
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
Labels: type.Enhancement

#96 Branch Sort Meeting
  src/main/java/seedu/address/logic/commands/SortMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortMeetingParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: priority.High

#103 Update DG with traversal of commands
  docs/DeveloperGuide.md
Labels: type.Documentation

#107 Update UG About section
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation

#108 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ui_mockup.png
Labels: type.Documentation

#109 Update `index.md`
  docs/index.md
Labels: type.Documentation

#112 Update dateTime sort to be ascending
  src/main/java/seedu/address/logic/commands/SortMeetingCommand.java
Labels: type.Bug

#116 Update UG
  docs/Documentation.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/jeremykhoo-nus.png
Labels: priority.High, type.Documentation

#115 Branch update addm
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/SortMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, type.Refactor

#128 Update Help Command
  src/main/java/seedu/quickcontacts/logic/commands/AddCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ClearCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/DeleteCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/EditCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/EditMeetingsCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ExitCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ExportMeetingsCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ExportPersonsCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/FindCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/HelpCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ImportMeetingsCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ImportPersonsCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ListCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/SortMeetingCommand.java
  src/main/java/seedu/quickcontacts/logic/commands/ViewMeetingsCommand.java
  src/main/java/seedu/quickcontacts/logic/parser/HelpCommandParser.java
  src/main/java/seedu/quickcontacts/logic/parser/QuickContactsParser.java
  src/main/java/seedu/quickcontacts/ui/HelpWindow.java
  src/test/java/seedu/quickcontacts/logic/parser/QuickContactsParserTest.java
Labels: type.Enhancement
